apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-news-db
  namespace: kube-news
spec:
  refreshInterval: 30m  # More frequent refresh in prod for rotation
  data:
    - secretKey: host
      remoteRef:
        key: /kube-news/prod/db
        property: host
    - secretKey: username
      remoteRef:
        key: /kube-news/prod/db
        property: username
    - secretKey: password
      remoteRef:
        key: /kube-news/prod/db
        property: password
