apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets
spec:
  provider:
    aws:
      # Dev uses SSM Parameter Store (free tier)
      service: ParameterStore
      region: us-east-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-news-db
  namespace: kube-news
spec:
  data:
    - secretKey: host
      remoteRef:
        key: /kube-news/dev/db/host
    - secretKey: username
      remoteRef:
        key: /kube-news/dev/db/username
    - secretKey: password
      remoteRef:
        key: /kube-news/dev/db/password
