apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-news
  namespace: kube-news
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: kube-news
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
